#!/usr/bin/env python3
"""
Script to modify the clipboard content in HTML reports generated by Hindsight.

This script transforms the content that gets copied to clipboard when a user
clicks the "Copy" button on an issue in the HTML report.

Changes made:
- Removes: "Hindsight (http://repoiq.ai)'s LLM analysis has found a potential issue"
- Adds: "StaticIntelligence: LLM Powered Static Analysis Tool found the following issue. Please do due diligence.\n\nIssue (AI):"

Usage:
    python change_clipboard_content.py --input <path_to_html>
"""

import argparse
import re
import sys
from pathlib import Path


def transform_clipboard_content(html_content: str) -> str:
    """
    Transform the clipboard content in the HTML file.
    
    This function finds the copyIssueToClipboard JavaScript function and modifies
    the content template to replace the Hindsight branding with StaticIntelligence branding.
    
    Args:
        html_content: The original HTML file content
        
    Returns:
        The modified HTML content with updated clipboard text
    """
    # The old text to remove
    old_text = "Hindsight (http://repoiq.ai)'s LLM analysis has found a potential issue"
    
    # The new text to add
    new_text = """StaticIntelligence: LLM Powered Static Analysis Tool found the following issue. Please do due diligence.

Issue (AI):"""
    
    # Pattern to find the content template in copyIssueToClipboard function
    # The template looks like:
    # const content = `Title: In ${functionName}() in ${fileName}, there is potential issue
    #
    # Hindsight (http://repoiq.ai)'s LLM analysis has found a potential issue
    #
    # In ${functionName}() in ${filePath}, there is potential issue
    
    # Replace the old text with the new text
    modified_content = html_content.replace(old_text, new_text)
    
    # Verify the replacement was made
    if modified_content == html_content:
        print("Warning: No changes were made. The target text was not found in the file.", file=sys.stderr)
        print(f"Looking for: '{old_text}'", file=sys.stderr)
        return html_content
    
    # Count how many replacements were made
    count = html_content.count(old_text)
    print(f"Successfully replaced {count} occurrence(s) of the Hindsight branding text.")
    
    return modified_content


def replace_repoiq_with_staticintelligence(html_content: str) -> str:
    """
    Replace all occurrences of 'Hindsight' (case insensitive) with 'StaticIntelligence'.
    
    Args:
        html_content: The HTML file content
        
    Returns:
        The modified HTML content with 'Hindsight' replaced by 'StaticIntelligence'
    """
    # Use case-insensitive regex to find and replace all occurrences of 'Hindsight'
    pattern = re.compile(r'repoiq', re.IGNORECASE)
    
    # Count occurrences before replacement
    count = len(pattern.findall(html_content))
    
    if count == 0:
        print("No occurrences of 'Hindsight' found in the file.")
        return html_content
    
    # Replace all occurrences
    modified_content = pattern.sub('StaticIntelligence', html_content)
    
    print(f"Successfully replaced {count} occurrence(s) of 'Hindsight' with 'StaticIntelligence'.")
    
    return modified_content


def main():
    """Main entry point for the script."""
    parser = argparse.ArgumentParser(
        description="Transform clipboard content in Hindsight HTML reports",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Example:
    python change_clipboard_content.py --input report.html
    
This will modify the HTML file in place, changing the text that gets copied
to clipboard when users click the "Copy" button on issues.
        """
    )
    
    parser.add_argument(
        "--input",
        required=True,
        type=str,
        help="Path to the HTML report file to modify (modified in place)"
    )
    
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show what would be changed without modifying the file"
    )
    
    args = parser.parse_args()
    
    # Validate input file exists
    input_path = Path(args.input)
    if not input_path.exists():
        print(f"Error: Input file not found: {args.input}", file=sys.stderr)
        sys.exit(1)
    
    if not input_path.is_file():
        print(f"Error: Input path is not a file: {args.input}", file=sys.stderr)
        sys.exit(1)
    
    # Read the input file
    try:
        html_content = input_path.read_text(encoding="utf-8")
    except Exception as e:
        print(f"Error reading input file: {e}", file=sys.stderr)
        sys.exit(1)
    
    # Transform the content
    modified_content = transform_clipboard_content(html_content)
    
    # Replace all occurrences of 'Hindsight' with 'StaticIntelligence'
    modified_content = replace_repoiq_with_staticintelligence(modified_content)
    
    if args.dry_run:
        print("\n--- Dry run mode: No changes written to disk ---")
        if modified_content != html_content:
            print("Changes would be made to the file.")
        else:
            print("No changes would be made.")
        return
    
    # Write the modified content back to the input file (in place)
    try:
        input_path.write_text(modified_content, encoding="utf-8")
        print(f"Successfully modified file in place: {input_path}")
    except Exception as e:
        print(f"Error writing output file: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()