#!/usr/bin/env python3
"""
Validation script for AST analysis results generated by code_analyzer.

This script validates the consistency and correctness of JSON files generated
by ast_util when code_analyzer is run in the code_insights directory.
"""

import argparse
import json
import os
import sys
from pathlib import Path
from typing import Dict, List, Set, Any, Optional, Tuple
import orjson


class ValidationResults:
    """Container for validation results categorized by check type."""
    
    def __init__(self):
        self.errors = {
            'functions_invoked_missing': [],
            'data_types_invalid': [],
            'invalid_file_paths_call_graph': [],
            'invalid_file_paths_data_types': [],
            'functions_missing_in_merged': [],
            'invalid_json_schema': [],
            'file_loading': []
        }
        self.warnings = []
        self.info = []
    
    def add_error(self, category: str, message: str, details: Dict[str, Any] = None):
        """Add an error to the specified category."""
        error_entry = {'message': message}
        if details:
            error_entry['details'] = details
        self.errors[category].append(error_entry)
    
    def add_warning(self, message: str):
        """Add a warning message."""
        self.warnings.append(message)
    
    def add_info(self, message: str):
        """Add an info message."""
        self.info.append(message)
    
    def has_errors(self) -> bool:
        """Check if there are any errors."""
        return any(self.errors.values())
    
    def get_total_error_count(self) -> int:
        """Get total number of errors across all categories."""
        return sum(len(errors) for errors in self.errors.values())


class ASTValidator:
    """Main validator class for AST analysis results."""
    
    def __init__(self, repo_root: str,
                 code_insights_dir: Optional[str] = None,
                 functions_file: Optional[str] = None,
                 call_graph_file: Optional[str] = None,
                 classes_file: Optional[str] = None):
        self.repo_root = Path(repo_root)
        self.code_insights_dir = code_insights_dir
        self.functions_file = functions_file
        self.call_graph_file = call_graph_file
        self.classes_file = classes_file
        self.results = ValidationResults()
        
        # Resolve file paths
        self._resolve_file_paths()
    
    def _resolve_file_paths(self):
        """Resolve file paths based on provided arguments."""
        if self.code_insights_dir:
            # Use default filenames when directory is provided
            base_path = Path(self.code_insights_dir)
            if not self.functions_file:
                self.functions_file = base_path / "merged_functions.json"
            if not self.call_graph_file:
                self.call_graph_file = base_path / "merged_call_graph.json"
            if not self.classes_file:
                self.classes_file = base_path / "merged_defined_classes.json"
        
        # Convert to Path objects for easier handling
        if self.functions_file:
            self.functions_file = Path(self.functions_file)
        if self.call_graph_file:
            self.call_graph_file = Path(self.call_graph_file)
        if self.classes_file:
            self.classes_file = Path(self.classes_file)
    
    def _validate_file_exists(self, file_path: Path, file_description: str) -> bool:
        """Check if file exists and is readable."""
        try:
            if not file_path or not file_path.exists():
                self.results.add_error('file_loading', f"{file_description} not found: {file_path}")
                return False
            
            if not file_path.is_file():
                self.results.add_error('file_loading', f"{file_description} is not a file: {file_path}")
                return False
            
            # Try to open and read first few bytes to check if it's readable
            with open(file_path, 'r', encoding='utf-8') as f:
                f.read(1)
            
            return True
        except Exception as e:
            self.results.add_error('file_loading', f"Error accessing {file_description}: {e}")
            return False
    
    def _validate_json_basic_structure(self, file_path: Path) -> Dict[str, Any]:
        """Validate basic JSON structure by checking file format without full parsing."""
        try:
            with open(file_path, 'r', encoding='utf-8') as f:
                # Read first line to check if it starts with {
                first_line = f.readline().strip()
                if not first_line.startswith('{'):
                    self.results.add_error('invalid_json_schema', f"File {file_path} does not start with JSON object")
                    return {}
                
                # Read a few more lines to identify the structure
                f.seek(0)  # Reset to beginning
                lines = []
                for i in range(10):  # Read first 10 lines to identify structure
                    line = f.readline()
                    if not line:
                        break
                    lines.append(line.strip())
                
                content = '\n'.join(lines)
                
                # Identify file type based on content patterns
                # Check for classes file first (most specific pattern)
                if 'data_type_to_location_and_checksum' in content:
                    return {'type': 'classes', 'valid_start': True}
                elif 'call_graph' in content:
                    return {'type': 'call_graph', 'valid_start': True}
                elif 'checksum' in content and 'code' in content:
                    return {'type': 'functions', 'valid_start': True}
                else:
                    return {'type': 'unknown', 'valid_start': True}
                    
        except Exception as e:
            self.results.add_error('file_loading', f"Error validating JSON structure from {file_path}: {e}")
            return {}
    
    def _sample_json_keys(self, file_path: Path, max_keys: int = 50) -> Set[str]:
        """Sample top-level keys from JSON file without loading entire file."""
        keys = set()
        try:
            # Try to peek at structure first
            sample_data = self._peek_json_structure(file_path)
            if sample_data:
                keys.update(list(sample_data.keys())[:max_keys])
            
            # If we didn't get enough keys, try reading line by line for more
            if len(keys) < max_keys:
                with open(file_path, 'r', encoding='utf-8') as f:
                    f.readline()  # Skip opening brace
                    for _ in range(max_keys * 2):  # Read more lines to find keys
                        line = f.readline().strip()
                        if not line or line == '}':
                            break
                        # Look for JSON key pattern: "key":
                        if line.startswith('"') and '":' in line:
                            key = line.split('":')[0].strip('"')
                            keys.add(key)
                            if len(keys) >= max_keys:
                                break
        except Exception as e:
            self.results.add_error('file_loading', f"Error sampling JSON keys from {file_path}: {e}")
        return keys
    
    def _peek_json_structure(self, file_path: Path, max_entries: int = 10) -> Dict[str, Any]:
        """Peek at JSON structure to get a sample of the data without loading entire file."""
        try:
            with open(file_path, 'rb') as f:
                # Read first chunk to get structure
                chunk_size = min(8192, file_path.stat().st_size)  # Read up to 8KB or file size
                chunk = f.read(chunk_size).decode('utf-8', errors='ignore')
                
                # Try to find a complete JSON object within the chunk
                brace_count = 0
                json_end = -1
                
                for i, char in enumerate(chunk):
                    if char == '{':
                        brace_count += 1
                    elif char == '}':
                        brace_count -= 1
                        if brace_count == 0:
                            json_end = i + 1
                            break
                
                if json_end > 0:
                    # Try to parse the complete JSON object
                    json_str = chunk[:json_end]
                    return orjson.loads(json_str.encode('utf-8'))
                else:
                    # Fallback: try to parse the entire chunk as JSON
                    return orjson.loads(chunk.encode('utf-8'))
                    
        except Exception as e:
            self.results.add_error('file_loading', f"Error peeking at JSON structure from {file_path}: {e}")
            return {}
    
    def _validate_functions_schema(self, file_path: Path) -> bool:
        """Validate merged_functions.json schema without loading entire file."""
        try:
            # Check basic structure
            structure_info = self._validate_json_basic_structure(file_path)
            if not structure_info.get('valid_start'):
                self.results.add_error('invalid_json_schema', "Invalid JSON format in functions file")
                return False
            
            if structure_info.get('type') != 'functions':
                self.results.add_error(
                    'invalid_json_schema',
                    "Functions file does not contain expected 'checksum' and 'code' properties"
                )
                return False
            
            self.results.add_info("Validated basic schema for merged_functions.json")
            return True
        except Exception as e:
            self.results.add_error('invalid_json_schema', f"Error validating functions schema: {e}")
            return False
    
    def _validate_call_graph_schema(self, file_path: Path) -> bool:
        """Validate merged_call_graph.json schema without loading entire file."""
        try:
            # Check basic structure
            structure_info = self._validate_json_basic_structure(file_path)
            if not structure_info.get('valid_start'):
                self.results.add_error('invalid_json_schema', "Invalid JSON format in call graph file")
                return False
            
            if structure_info.get('type') != 'call_graph':
                self.results.add_error(
                    'invalid_json_schema',
                    "Call graph file does not contain expected 'call_graph' key"
                )
                return False
            
            self.results.add_info("Validated basic schema for merged_call_graph.json")
            return True
        except Exception as e:
            self.results.add_error('invalid_json_schema', f"Error validating call graph schema: {e}")
            return False
    
    def _validate_classes_schema(self, file_path: Path) -> bool:
        """Validate merged_defined_classes.json schema without loading entire file."""
        try:
            # Check basic structure
            structure_info = self._validate_json_basic_structure(file_path)
            if not structure_info.get('valid_start'):
                self.results.add_error('invalid_json_schema', "Invalid JSON format in classes file")
                return False
            
            if structure_info.get('type') != 'classes':
                self.results.add_error(
                    'invalid_json_schema',
                    "Classes file does not contain expected 'data_type_to_location_and_checksum' key"
                )
                return False
            
            self.results.add_info("Validated basic schema for merged_defined_classes.json")
            return True
        except Exception as e:
            self.results.add_error('invalid_json_schema', f"Error validating classes schema: {e}")
            return False
    
    def validate_file_paths_in_call_graph(self):
        """Validate file paths in call graph using orjson."""
        if not self.call_graph_file or not self._validate_file_exists(self.call_graph_file, "merged_call_graph.json"):
            return
        
        try:
            file_count = 0
            error_count = 0
            
            with open(self.call_graph_file, 'rb') as f:
                data = orjson.loads(f.read())
                
                if 'call_graph' not in data:
                    self.results.add_error('invalid_json_schema', "Missing 'call_graph' key in call graph file")
                    return
                
                call_graph = data['call_graph']
                if not isinstance(call_graph, list):
                    self.results.add_error('invalid_json_schema', "'call_graph' should be a list")
                    return
                
                for file_entry in call_graph:
                    if isinstance(file_entry, dict) and 'file' in file_entry:
                        file_path = file_entry['file']
                        file_count += 1
                        
                        # Check if file exists relative to repository root
                        if Path(file_path).is_absolute():
                            path_obj = Path(file_path)
                        else:
                            path_obj = self.repo_root / file_path
                        
                        if not path_obj.exists():
                            error_count += 1
                            self.results.add_error(
                                'invalid_file_paths_call_graph',
                                f"File path in call graph does not exist: {file_path} (resolved to: {path_obj})",
                                {'file_path': file_path, 'resolved_path': str(path_obj)}
                            )
            
            self.results.add_info(f"Validated {file_count} file paths in call graph, found {error_count} invalid paths")
                    
        except Exception as e:
            self.results.add_error('file_loading', f"Error validating call graph file paths: {e}")
    
    def validate_file_paths_in_classes(self):
        """Validate file paths in defined classes using orjson."""
        if not self.classes_file or not self._validate_file_exists(self.classes_file, "merged_defined_classes.json"):
            return
        
        try:
            file_count = 0
            error_count = 0
            
            with open(self.classes_file, 'rb') as f:
                data = orjson.loads(f.read())
                
                if 'data_type_to_location_and_checksum' not in data:
                    self.results.add_error('invalid_json_schema', "Missing 'data_type_to_location_and_checksum' key in classes file")
                    return
                
                classes_data = data['data_type_to_location_and_checksum']
                if not isinstance(classes_data, dict):
                    self.results.add_error('invalid_json_schema', "'data_type_to_location_and_checksum' should be a dictionary")
                    return
                
                for class_name, class_info in classes_data.items():
                    if isinstance(class_info, dict) and 'code' in class_info:
                        code_entries = class_info['code']
                        if isinstance(code_entries, list):
                            for code_entry in code_entries:
                                if isinstance(code_entry, dict) and 'file_name' in code_entry:
                                    file_name = code_entry['file_name']
                                    file_count += 1
                                    
                                    # Check if file exists relative to repository root
                                    if Path(file_name).is_absolute():
                                        path_obj = Path(file_name)
                                    else:
                                        path_obj = self.repo_root / file_name
                                    
                                    if not path_obj.exists():
                                        error_count += 1
                                        self.results.add_error(
                                            'invalid_file_paths_data_types',
                                            f"File path in class definition does not exist: {file_name} (resolved to: {path_obj})",
                                            {
                                                'file_name': file_name,
                                                'resolved_path': str(path_obj),
                                                'class_name': class_name
                                            }
                                        )
            
            self.results.add_info(f"Validated {file_count} file paths in class definitions, found {error_count} invalid paths")
                    
        except Exception as e:
            self.results.add_error('file_loading', f"Error validating class file paths: {e}")
    
    def validate_functions_invoked_in_merged_functions(self):
        """Validate that functions_invoked entries exist in merged_functions.json."""
        if not self.functions_file or not self._validate_file_exists(self.functions_file, "merged_functions.json"):
            return
        if not self.call_graph_file or not self._validate_file_exists(self.call_graph_file, "merged_call_graph.json"):
            return
        
        try:
            # Load all functions from merged_functions.json
            merged_functions = set()
            
            with open(self.functions_file, 'rb') as f:
                data = orjson.loads(f.read())
                
                # Handle different possible structures
                if 'function_to_location' in data:
                    # New format with function_to_location wrapper
                    functions_data = data['function_to_location']
                    if isinstance(functions_data, dict):
                        for func_name in functions_data.keys():
                            merged_functions.add(func_name)
                elif isinstance(data, dict):
                    # Direct function mapping format
                    for func_name in data.keys():
                        merged_functions.add(func_name)
            
            # Load call graph and extract all functions_invoked
            functions_invoked_set = set()
            
            with open(self.call_graph_file, 'rb') as f:
                data = orjson.loads(f.read())
                
                if 'call_graph' not in data:
                    self.results.add_error('invalid_json_schema', "Missing 'call_graph' key in call graph file")
                    return
                
                call_graph = data['call_graph']
                if not isinstance(call_graph, list):
                    self.results.add_error('invalid_json_schema', "'call_graph' should be a list")
                    return
                
                # Extract functions_invoked from call graph entries
                for file_entry in call_graph:
                    if isinstance(file_entry, dict) and 'functions' in file_entry:
                        functions = file_entry['functions']
                        if isinstance(functions, list):
                            for func_entry in functions:
                                if isinstance(func_entry, dict) and 'functions_invoked' in func_entry:
                                    functions_invoked = func_entry['functions_invoked']
                                    if isinstance(functions_invoked, list):
                                        for func_name in functions_invoked:
                                            if isinstance(func_name, str):
                                                functions_invoked_set.add(func_name)
            
            # Validate functions_invoked against merged_functions
            missing_functions = functions_invoked_set - merged_functions
            
            for func_name in missing_functions:
                self.results.add_error(
                    'functions_invoked_missing',
                    f"Function '{func_name}' in functions_invoked array not found in merged_functions.json",
                    {'function_name': func_name}
                )
            
            self.results.add_info(f"Validated {len(functions_invoked_set)} functions_invoked entries against {len(merged_functions)} merged functions")
            
        except Exception as e:
            self.results.add_error('file_loading', f"Error validating functions_invoked: {e}")
    
    def validate_data_types_used_in_classes(self):
        """Validate that data_types_used entries exist in merged_defined_classes.json."""
        if not self.classes_file or not self._validate_file_exists(self.classes_file, "merged_defined_classes.json"):
            return
        
        try:
            # Load defined data types
            defined_data_types = set()
            
            with open(self.classes_file, 'rb') as f:
                data = orjson.loads(f.read())
                
                if 'data_type_to_location_and_checksum' not in data:
                    self.results.add_error('invalid_json_schema', "Missing 'data_type_to_location_and_checksum' key in classes file")
                    return
                
                classes_data = data['data_type_to_location_and_checksum']
                if not isinstance(classes_data, dict):
                    self.results.add_error('invalid_json_schema', "'data_type_to_location_and_checksum' should be a dictionary")
                    return
                
                # Add all data type names
                for data_type_name in classes_data.keys():
                    defined_data_types.add(data_type_name)
            
            # Collect all data_types_used from analysis files
            data_types_used_set = set()
            
            if self.code_insights_dir:
                import glob
                pattern = str(Path(self.code_insights_dir) / "*.json")
                analysis_files = glob.glob(pattern)
                
                for file_path in analysis_files:
                    if 'merged_' in file_path:  # Skip merged files
                        continue
                        
                    try:
                        with open(file_path, 'rb') as f:
                            file_data = orjson.loads(f.read())
                            
                            # Extract data_types_used from various possible structures
                            def extract_data_types_used(obj):
                                if isinstance(obj, dict):
                                    if 'data_types_used' in obj and isinstance(obj['data_types_used'], list):
                                        for type_name in obj['data_types_used']:
                                            if isinstance(type_name, str):
                                                data_types_used_set.add(type_name)
                                    
                                    # Recursively check nested objects
                                    for value in obj.values():
                                        if isinstance(value, (dict, list)):
                                            extract_data_types_used(value)
                                elif isinstance(obj, list):
                                    for item in obj:
                                        if isinstance(item, (dict, list)):
                                            extract_data_types_used(item)
                            
                            extract_data_types_used(file_data)
                            
                    except Exception:
                        continue
            
            # Validate data_types_used against defined classes
            missing_data_types = data_types_used_set - defined_data_types
            
            for data_type_name in missing_data_types:
                self.results.add_error(
                    'data_types_invalid',
                    f"Data type '{data_type_name}' in data_types_used array not found in merged_defined_classes.json",
                    {'data_type_name': data_type_name}
                )
            
            self.results.add_info(f"Validated {len(data_types_used_set)} data_types_used entries against {len(defined_data_types)} defined data types")
            
        except Exception as e:
            self.results.add_error('file_loading', f"Error validating data_types_used: {e}")
    
    def validate_call_graph_functions_in_merged_functions(self):
        """Validate that every function in merged_call_graph.json has an entry in merged_functions.json."""
        if not self.call_graph_file or not self._validate_file_exists(self.call_graph_file, "merged_call_graph.json"):
            return
        if not self.functions_file or not self._validate_file_exists(self.functions_file, "merged_functions.json"):
            return
        
        try:
            # Load functions from merged_functions.json
            merged_functions = set()
            
            with open(self.functions_file, 'rb') as f:
                data = orjson.loads(f.read())
                
                # Handle different possible structures
                if 'function_to_location' in data:
                    # New format with function_to_location wrapper
                    functions_data = data['function_to_location']
                    if isinstance(functions_data, dict):
                        for func_name in functions_data.keys():
                            merged_functions.add(func_name)
                elif isinstance(data, dict):
                    # Direct function mapping format
                    for func_name in data.keys():
                        merged_functions.add(func_name)
            
            # Load functions from call graph
            call_graph_functions = set()
            
            with open(self.call_graph_file, 'rb') as f:
                data = orjson.loads(f.read())
                
                if 'call_graph' not in data:
                    self.results.add_error('invalid_json_schema', "Missing 'call_graph' key in call graph file")
                    return
                
                call_graph = data['call_graph']
                if not isinstance(call_graph, list):
                    self.results.add_error('invalid_json_schema', "'call_graph' should be a list")
                    return
                
                for file_entry in call_graph:
                    if isinstance(file_entry, dict) and 'functions' in file_entry:
                        functions = file_entry['functions']
                        if isinstance(functions, list):
                            for func_entry in functions:
                                if isinstance(func_entry, dict) and 'function' in func_entry:
                                    func_name = func_entry['function']
                                    if func_name:
                                        call_graph_functions.add(func_name)
            
            # Find functions in call graph that are missing from merged functions
            missing_in_merged = call_graph_functions - merged_functions
            
            for func_name in missing_in_merged:
                self.results.add_error(
                    'functions_missing_in_merged',
                    f"Function '{func_name}' in merged_call_graph.json not found in merged_functions.json",
                    {'function_name': func_name}
                )
            
            self.results.add_info(f"Validated {len(call_graph_functions)} call graph functions against {len(merged_functions)} merged functions")
            
        except Exception as e:
            self.results.add_error('file_loading', f"Error validating call graph functions in merged functions: {e}")
    
    def validate_basic_structure(self):
        """Validate basic JSON structure and schema without loading entire files."""
        # Validate functions file
        if self.functions_file and self._validate_file_exists(self.functions_file, "merged_functions.json"):
            self._validate_functions_schema(self.functions_file)
        
        # Validate call graph file
        if self.call_graph_file and self._validate_file_exists(self.call_graph_file, "merged_call_graph.json"):
            self._validate_call_graph_schema(self.call_graph_file)
        
        # Validate classes file
        if self.classes_file and self._validate_file_exists(self.classes_file, "merged_defined_classes.json"):
            self._validate_classes_schema(self.classes_file)
    
    def run_all_validations(self):
        """Run all validation checks."""
        self.results.add_info("Starting AST validation checks...")
        
        # Validate basic structure and schema
        self.validate_basic_structure()
        
        # Validate file paths (limited to avoid memory issues)
        self.validate_file_paths_in_call_graph()
        self.validate_file_paths_in_classes()
        
        # Validate cross-references between JSON files
        self.validate_functions_invoked_in_merged_functions()
        self.validate_data_types_used_in_classes()
        self.validate_call_graph_functions_in_merged_functions()
        
        self.results.add_info("Validation checks completed.")
    
    def print_results(self):
        """Print validation results in human-readable format."""
        print("=" * 80)
        print("AST VALIDATION RESULTS")
        print("=" * 80)
        
        # Print info messages
        if self.results.info:
            print("\n📋 INFORMATION:")
            for info in self.results.info:
                print(f"  ℹ️  {info}")
        
        # Print warnings
        if self.results.warnings:
            print("\n⚠️  WARNINGS:")
            for warning in self.results.warnings:
                print(f"  ⚠️  {warning}")
        
        # Print errors by category
        error_categories = {
            'functions_invoked_missing': "❌ FUNCTIONS INVOKED in merged_call_graph.json, but NOT PRESENT IN merged_functions.json",
            'data_types_invalid': "❌ DATA TYPES USED in analysis files, but NOT PRESENT IN merged_defined_classes.json",
            'invalid_file_paths_call_graph': "❌ INVALID FILE PATHS IN CALL GRAPH",
            'invalid_file_paths_data_types': "❌ INVALID FILE PATHS IN DATA TYPES",
            'functions_missing_in_merged': "❌ FUNCTIONS IN merged_call_graph.json, but NOT PRESENT IN merged_functions.json",
            'invalid_json_schema': "❌ INVALID JSON SCHEMA ERRORS",
            'file_loading': "❌ FILE LOADING ERRORS"
        }
        
        # Categories that should use compact format
        compact_categories = {'functions_invoked_missing', 'data_types_invalid', 'functions_missing_in_merged'}
        
        total_errors = 0
        for category, errors in self.results.errors.items():
            if errors:
                total_errors += len(errors)
                category_name = error_categories.get(category, f"❌ {category.upper()}")
                print(f"\n{category_name} ({len(errors)} errors):")
                
                if category in compact_categories:
                    # Use compact format for validation errors
                    for error in errors:
                        if 'details' in error and 'function_name' in error['details']:
                            print(f"- function_name: {error['details']['function_name']}")
                        elif 'details' in error and 'data_type_name' in error['details']:
                            print(f"- data_type_name: {error['details']['data_type_name']}")
                        else:
                            # Fallback for other compact categories
                            print(f"- {error['message']}")
                else:
                    # Use detailed format for other errors
                    for i, error in enumerate(errors, 1):
                        print(f"  {i}. {error['message']}")
                        if 'details' in error:
                            for key, value in error['details'].items():
                                print(f"     - {key}: {value}")
        
        # Summary
        print("\n" + "=" * 80)
        print("SUMMARY")
        print("=" * 80)
        
        if total_errors == 0:
            print("✅ All validation checks passed! No errors found.")
        else:
            print(f"❌ Found {total_errors} total errors across {sum(1 for errors in self.results.errors.values() if errors)} categories.")
        
        if self.results.warnings:
            print(f"⚠️  {len(self.results.warnings)} warnings found.")
        
        return total_errors == 0


def main():
    """Main entry point for the validation script."""
    parser = argparse.ArgumentParser(
        description="Validate AST analysis results generated by code_analyzer",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Using code_insights directory (uses default filenames)
  python validate_lang_ast.py --repo /path/to/repository --code-insights-dir /path/to/code_insights
  
  # Using specific file paths
  python validate_lang_ast.py --repo /path/to/repository --functions /path/to/merged_functions.json \\
                              --call-graph /path/to/merged_call_graph.json \\
                              --classes /path/to/merged_defined_classes.json
  
  # Mixed approach
  python validate_lang_ast.py --repo /path/to/repository --code-insights-dir /path/to/code_insights \\
                              --functions /custom/path/functions.json
        """
    )
    
    parser.add_argument(
        '--repo',
        type=str,
        required=True,
        help='Path to repository root directory (file paths in JSON are relative to this)'
    )
    
    parser.add_argument(
        '--code-insights-dir',
        type=str,
        help='Directory containing code_insights with default JSON files'
    )
    
    parser.add_argument(
        '--functions',
        type=str,
        help='Path to merged_functions.json file'
    )
    
    parser.add_argument(
        '--call-graph',
        type=str,
        help='Path to merged_call_graph.json file'
    )
    
    parser.add_argument(
        '--classes',
        type=str,
        help='Path to merged_defined_classes.json file'
    )
    
    args = parser.parse_args()
    
    # Validate arguments
    if not any([args.code_insights_dir, args.functions, args.call_graph, args.classes]):
        parser.error("At least one of --code-insights-dir or specific file paths must be provided")
    
    # Validate repository root exists
    if not Path(args.repo).exists():
        parser.error(f"Repository root directory does not exist: {args.repo}")
    
    # Create validator and run checks
    validator = ASTValidator(
        repo_root=args.repo,
        code_insights_dir=args.code_insights_dir,
        functions_file=args.functions,
        call_graph_file=args.call_graph,
        classes_file=args.classes
    )
    
    try:
        validator.run_all_validations()
        success = validator.print_results()
        
        # Exit with appropriate code
        sys.exit(0 if success else 1)
        
    except KeyboardInterrupt:
        print("\n\n❌ Validation interrupted by user")
        sys.exit(1)
    except Exception as e:
        print(f"\n\n❌ Unexpected error during validation: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()