#!/usr/bin/env python3
"""
call_graph_stats.py - Script to analyze merged_call_graph.json and print statistics.

This script uses the call_graph_util module to parse the call graph generated by ast_util
and compute various statistics about the graph structure.

NOTE: The core implementation has been moved to hindsight/core/lang_util/call_graph_util.py
This script now imports from that module.

Usage:
    python call_graph_stats.py -f <path_to_merged_functions_json>
    
Example:
    python call_graph_stats.py -f /Users/sgurivireddy/hindsight_artifacts/corelocation/code_insights/merged_call_graph.json
"""

import argparse
import json
import sys
import os
from pathlib import Path

# Add the project root to the path to import from hindsight
project_root = Path(__file__).parent.parent.parent
sys.path.insert(0, str(project_root))

# Import from the new location
from hindsight.core.lang_util.call_graph_util import (
    CallGraph,
    load_call_graph_from_json,
    print_statistics,
    generate_sample_callstacks
)


def main():
    """Main entry point for the script."""
    parser = argparse.ArgumentParser(
        description="Analyze merged_call_graph.json and print statistics."
    )
    parser.add_argument(
        "-f",
        metavar="<path>",
        required=True,
        help="Path to merged functions JSON file"
    )
    parser.add_argument(
        "-p",
        metavar="<level>",
        type=int,
        required=False,
        help="Print functions at the specified level number"
    )
    parser.add_argument(
        "-s",
        "--sample-callstacks",
        metavar="<path>",
        default="/tmp/sample_callstacks.txt",
        required=False,
        help="Path for sample callstacks output file (default: /tmp/sample_callstacks.txt)"
    )
    parser.add_argument(
        "-d",
        action="store_true",
        required=False,
        help="Print root nodes (functions with no callers)"
    )
    parser.add_argument(
        "-m",
        metavar="<count>",
        type=int,
        nargs="?",
        const=10,
        required=False,
        help="Print nodes with maximum edges (children + parents). Optionally specify count (default: 10)"
    )
    args = parser.parse_args()
    
    json_path = args.f
    
    # Check if file exists
    if not os.path.exists(json_path):
        print(f"Error: File not found: {json_path}")
        sys.exit(1)
    
    print(f"\nLoading call graph from: {json_path}")
    print()
    
    # Load the JSON file
    try:
        with open(json_path, 'r') as f:
            data = json.load(f)
    except json.JSONDecodeError as e:
        print(f"Error: Invalid JSON file: {e}")
        sys.exit(1)
    except Exception as e:
        print(f"Error reading file: {e}")
        sys.exit(1)
    
    # Parse the call graph
    print("Parsing call graph...")
    graph = load_call_graph_from_json(data)
    
    # If -d argument is provided, print root nodes and exit
    if args.d:
        root_nodes = sorted(graph.get_root_nodes())
        print(f"\nROOT NODES (functions with no callers):")
        print("-" * 60)
        print(f"  Total: {len(root_nodes)} functions")
        print()
        for node in root_nodes:
            print(f"  {node}")
        print()
        return
    
    # If -m argument is provided, print nodes with maximum edges and exit
    if args.m is not None:
        count = args.m
        # Calculate total edges (children + parents) for each node
        node_edge_counts = []
        for node in graph.nodes:
            children = len(graph.get_outgoing_edges(node))
            parents = len(graph.get_incoming_edges(node))
            total = children + parents
            node_edge_counts.append((node, total, children, parents))
        
        # Sort by total edges descending
        node_edge_counts.sort(key=lambda x: x[1], reverse=True)
        
        # Get top N nodes
        top_nodes = node_edge_counts[:count]
        
        print(f"\nNODES WITH MAXIMUM EDGES (top {count}):")
        print("-" * 80)
        print(f"  {'Function':<50} {'Total':>8} {'Children':>10} {'Parents':>10}")
        print("-" * 80)
        for node, total, children, parents in top_nodes:
            display_name = node if len(node) <= 48 else node[:45] + "..."
            print(f"  {display_name:<50} {total:>8} {children:>10} {parents:>10}")
        print("-" * 80)
        print(f"  Total nodes in graph: {len(graph.nodes)}")
        print()
        return
    
    # Compute statistics with cycle breaking at depth 20
    print("Computing statistics (breaking cycles at depth 20)...")
    print()
    
    stats = graph.get_statistics(max_depth=20)
    
    # Print the statistics
    print_statistics(stats)
    
    # Additional detailed output
    print("\nDETAILED LEVEL BREAKDOWN:")
    print("-" * 60)
    
    levels = graph.compute_levels_from_bottom(max_depth=20)
    
    # If -p argument is provided, print functions at that level and exit
    if args.p is not None:
        target_level = args.p
        if target_level in levels:
            nodes = sorted(levels[target_level])
            print(f"\nFUNCTIONS AT LEVEL {target_level}:")
            print("-" * 60)
            print(f"  Total: {len(nodes)} functions")
            print()
            for node in nodes:
                print(f"  {node}")
            print()
        else:
            available_levels = sorted(levels.keys())
            print(f"\nError: Level {target_level} not found in the graph.")
            print(f"Available levels: {min(available_levels)} to {max(available_levels)}")
            sys.exit(1)
        return
    
    total_nodes = 0
    for level in sorted(levels.keys()):
        nodes = levels[level]
        total_nodes += len(nodes)
        percentage = (len(nodes) / stats['num_nodes'] * 100) if stats['num_nodes'] > 0 else 0
        print(f"  Level {level:3d}: {len(nodes):6d} nodes ({percentage:5.1f}%)")
    
    print("-" * 60)
    print(f"  Total:     {total_nodes:6d} nodes")
    print()
    
    # Show some sample nodes at each level (first 3 nodes)
    print("\nSAMPLE NODES PER LEVEL (first 3):")
    print("-" * 60)
    for level in sorted(levels.keys())[:20]:  # Show first 20 levels
        nodes = list(levels[level])[:3]
        print(f"  Level {level}:")
        for node in nodes:
            # Truncate long function names
            display_name = node if len(node) <= 60 else node[:57] + "..."
            print(f"    - {display_name}")
    
    if len(levels) > 20:
        print(f"  ... and {len(levels) - 20} more levels")
    print()
    
    # Detect and report cycles
    print("\nCYCLE DETECTION:")
    print("-" * 60)
    cycles = graph.detect_cycles(max_depth=20)
    if cycles:
        print(f"  Found {len(cycles)} cycle(s) in the graph")
        print("  (Cycles are broken at depth 20 for path counting)")
        # Show first few cycles
        for i, cycle in enumerate(cycles[:5]):
            print(f"\n  Cycle {i+1}:")
            for node in cycle[:5]:
                display_name = node if len(node) <= 50 else node[:47] + "..."
                print(f"    -> {display_name}")
            if len(cycle) > 5:
                print(f"    ... ({len(cycle) - 5} more nodes in cycle)")
        if len(cycles) > 5:
            print(f"\n  ... and {len(cycles) - 5} more cycles")
    else:
        print("  No cycles detected (graph is a DAG)")
    print()
    
    # Summary
    print("\nSUMMARY:")
    print("=" * 60)
    print(f"  Graph Depth:              {stats['graph_depth']}")
    print(f"  Number of Nodes:          {stats['num_nodes']}")
    print(f"  Number of Edges:          {stats['num_edges']}")
    print(f"  Mean Edges per Node:      {stats['mean_edges_per_node']:.2f}")
    print(f"  Median Edges per Node:    {stats['median_edges_per_node']:.2f}")
    print(f"  Total Possible Paths:     {stats['total_paths']}")
    print("=" * 60)
    
    # Generate sample callstacks to file
    output_path = args.sample_callstacks
    print(f"\nGenerating sample callstacks (max 10 per level)...")
    generate_sample_callstacks(graph, levels, output_path)
    print(f"Sample callstacks have been written to: {output_path}")


if __name__ == "__main__":
    main()
