"""
GraphUtil.py - Graph utility module for analyzing call graphs.

This module provides graph algorithms for analyzing call graphs generated by ast_util.
It treats the call graph as a directed graph where:
- Nodes are functions
- Edges are function invocations (from caller to callee)

NOTE: The core implementation has been moved to hindsight/core/lang_util/call_graph_util.py
This file now re-exports from that module for backward compatibility.
"""

import sys
from pathlib import Path

# Add the project root to the path to import from hindsight
project_root = Path(__file__).parent.parent.parent
sys.path.insert(0, str(project_root))

# Re-export everything from the new location for backward compatibility
from hindsight.core.lang_util.call_graph_util import (
    CallGraph,
    load_call_graph_from_json,
    print_statistics,
    generate_sample_callstacks
)

# Keep the __all__ for explicit exports
__all__ = [
    'CallGraph',
    'load_call_graph_from_json',
    'print_statistics',
    'generate_sample_callstacks'
]


if __name__ == "__main__":
    # Example usage - kept for backward compatibility
    import json
    
    if len(sys.argv) < 2:
        print("Usage: python GraphUtil.py <path_to_merged_call_graph.json>")
        sys.exit(1)
    
    json_path = sys.argv[1]
    
    with open(json_path, 'r') as f:
        data = json.load(f)
    
    graph = load_call_graph_from_json(data)
    stats = graph.get_statistics(max_depth=20)
    print_statistics(stats)
