"""
call_graph_util.py - Graph utility module for analyzing call graphs.

This module provides graph algorithms for analyzing call graphs generated by ast_util.
It treats the call graph as a directed graph where:
- Nodes are functions
- Edges are function invocations (from caller to callee)

This module was refactored from dev/call_graph_util/GraphUtil.py to be part of the
core lang_util package for reuse by data_flow_analyzer and other components.
"""

from collections import defaultdict, deque
from typing import Dict, List, Set, Tuple, Optional, Any
import statistics
import logging

logger = logging.getLogger(__name__)


class CallGraph:
    """
    A directed graph representation of a call graph.
    
    Nodes are function names (strings).
    Edges represent function calls (from caller to callee).
    """
    
    def __init__(self):
        """Initialize an empty call graph."""
        self.nodes: Set[str] = set()
        self.edges: Dict[str, Set[str]] = defaultdict(set)  # caller -> set of callees
        self.reverse_edges: Dict[str, Set[str]] = defaultdict(set)  # callee -> set of callers
    
    def add_node(self, node: str) -> None:
        """Add a node to the graph."""
        self.nodes.add(node)
    
    def add_edge(self, from_node: str, to_node: str) -> None:
        """Add a directed edge from from_node to to_node."""
        self.nodes.add(from_node)
        self.nodes.add(to_node)
        self.edges[from_node].add(to_node)
        self.reverse_edges[to_node].add(from_node)
    
    def get_num_nodes(self) -> int:
        """Return the number of nodes in the graph."""
        return len(self.nodes)
    
    def get_num_edges(self) -> int:
        """Return the total number of edges in the graph."""
        return sum(len(callees) for callees in self.edges.values())
    
    def get_outgoing_edges(self, node: str) -> Set[str]:
        """Return the set of nodes that this node calls."""
        return self.edges.get(node, set())
    
    def get_incoming_edges(self, node: str) -> Set[str]:
        """Return the set of nodes that call this node."""
        return self.reverse_edges.get(node, set())
    
    def get_edges_per_node_stats(self) -> Dict[str, float]:
        """
        Calculate statistics for edges per node.
        
        Returns:
            Dictionary with 'mean', 'median', 'min', 'max' keys.
        """
        edge_counts = [len(self.edges.get(node, set())) for node in self.nodes]
        
        if not edge_counts:
            return {'mean': 0.0, 'median': 0.0, 'min': 0, 'max': 0}
        
        return {
            'mean': statistics.mean(edge_counts),
            'median': statistics.median(edge_counts),
            'min': min(edge_counts),
            'max': max(edge_counts)
        }
    
    def get_leaf_nodes(self) -> Set[str]:
        """
        Return nodes that don't invoke any other functions (level 0 nodes).
        These are the bottom-most nodes in the call hierarchy.
        """
        return {node for node in self.nodes if len(self.edges.get(node, set())) == 0}
    
    def get_root_nodes(self) -> Set[str]:
        """
        Return nodes that are not invoked by any other functions.
        These are the top-most nodes in the call hierarchy.
        """
        return {node for node in self.nodes if len(self.reverse_edges.get(node, set())) == 0}
    
    def compute_levels_from_bottom(self, max_depth: int = 20) -> Dict[int, Set[str]]:
        """
        Compute levels from bottom up.
        Level 0: nodes that don't invoke any functions (leaf nodes)
        Level 1: nodes that only invoke level 0 nodes
        Level N: nodes that invoke at least one level N-1 node
        
        Args:
            max_depth: Maximum depth to prevent infinite loops in cycles.
        
        Returns:
            Dictionary mapping level number to set of nodes at that level.
        """
        levels: Dict[int, Set[str]] = defaultdict(set)
        node_levels: Dict[str, int] = {}
        
        # Start with leaf nodes (level 0)
        leaf_nodes = self.get_leaf_nodes()
        for node in leaf_nodes:
            node_levels[node] = 0
            levels[0].add(node)
        
        # Process remaining nodes
        remaining = self.nodes - leaf_nodes
        changed = True
        iteration = 0
        
        while changed and iteration < max_depth:
            changed = False
            iteration += 1
            still_remaining = set()
            
            for node in remaining:
                callees = self.edges.get(node, set())
                if not callees:
                    # This shouldn't happen as we already handled leaf nodes
                    node_levels[node] = 0
                    levels[0].add(node)
                    changed = True
                    continue
                
                # Check if all callees have been assigned levels
                callee_levels = []
                all_assigned = True
                for callee in callees:
                    if callee in node_levels:
                        callee_levels.append(node_levels[callee])
                    elif callee == node:
                        # Self-recursion - treat as if callee is at level 0
                        callee_levels.append(0)
                    else:
                        all_assigned = False
                        break
                
                if all_assigned and callee_levels:
                    level = max(callee_levels) + 1
                    node_levels[node] = level
                    levels[level].add(node)
                    changed = True
                else:
                    still_remaining.add(node)
            
            remaining = still_remaining
        
        # Assign remaining nodes (in cycles) to max_depth level
        if remaining:
            for node in remaining:
                node_levels[node] = max_depth
                levels[max_depth].add(node)
        
        return dict(levels)
    
    def compute_graph_depth(self, max_depth: int = 20) -> int:
        """
        Compute the depth of the graph (longest path from any root to any leaf).
        Cycles are broken at max_depth.
        
        Args:
            max_depth: Maximum depth to prevent infinite loops in cycles.
        
        Returns:
            The depth of the graph.
        """
        levels = self.compute_levels_from_bottom(max_depth)
        if not levels:
            return 0
        return max(levels.keys())
    
    def detect_cycles(self, max_depth: int = 20) -> List[List[str]]:
        """
        Detect cycles in the graph using DFS.
        
        Args:
            max_depth: Maximum depth for cycle detection.
        
        Returns:
            List of cycles found (each cycle is a list of nodes).
        """
        cycles = []
        visited = set()
        rec_stack = set()
        path = []
        
        def dfs(node: str, depth: int = 0) -> None:
            if depth > max_depth:
                return
            
            visited.add(node)
            rec_stack.add(node)
            path.append(node)
            
            for neighbor in self.edges.get(node, set()):
                if neighbor not in visited:
                    dfs(neighbor, depth + 1)
                elif neighbor in rec_stack:
                    # Found a cycle
                    cycle_start = path.index(neighbor)
                    cycle = path[cycle_start:] + [neighbor]
                    cycles.append(cycle)
            
            path.pop()
            rec_stack.remove(node)
        
        for node in self.nodes:
            if node not in visited:
                dfs(node)
        
        return cycles
    
    def count_paths_dag(self, max_depth: int = 20) -> int:
        """
        Count total number of paths in the graph after breaking cycles.
        Uses dynamic programming on a DAG (after removing back edges).
        
        A path is defined as a sequence from any node to any leaf node.
        Cycles are broken by removing back edges (edges that go from lower
        to higher or equal levels, which would create cycles).
        
        Args:
            max_depth: Maximum depth for breaking cycles.
        
        Returns:
            Total number of paths in the graph.
        """
        # First, compute levels to identify back edges (edges that create cycles)
        levels = self.compute_levels_from_bottom(max_depth)
        node_levels = {}
        for level, nodes in levels.items():
            for node in nodes:
                node_levels[node] = level
        
        # Create a DAG by only keeping edges that go from higher to STRICTLY lower levels
        # This ensures we break all cycles including self-loops and same-level cycles
        dag_edges: Dict[str, Set[str]] = defaultdict(set)
        for node in self.nodes:
            node_level = node_levels.get(node, 0)
            for callee in self.edges.get(node, set()):
                # Skip self-loops
                if callee == node:
                    continue
                callee_level = node_levels.get(callee, 0)
                # Only keep edge if it goes to a STRICTLY lower level
                # This breaks all cycles since cycles require at least one back edge
                if callee_level < node_level:
                    dag_edges[node].add(callee)
        
        # Count paths using memoization on the DAG
        # paths_from[node] = number of paths starting from node to any leaf
        paths_from: Dict[str, int] = {}
        
        # Process nodes in level order (bottom-up) to ensure dependencies are computed first
        for level in sorted(levels.keys()):
            for node in levels[level]:
                callees = dag_edges.get(node, set())
                
                if not callees:
                    # Leaf node or node with all edges removed - one path (the node itself)
                    paths_from[node] = 1
                else:
                    # Sum of paths through all callees (all callees are at lower levels, so already computed)
                    total = sum(paths_from.get(callee, 1) for callee in callees)
                    paths_from[node] = total if total > 0 else 1
        
        # Count total paths from all nodes
        total_paths = sum(paths_from.values())
        
        return total_paths
    
    def get_statistics(self, max_depth: int = 20) -> Dict[str, Any]:
        """
        Get comprehensive statistics about the graph.
        
        Args:
            max_depth: Maximum depth for cycle breaking.
        
        Returns:
            Dictionary containing all statistics.
        """
        levels = self.compute_levels_from_bottom(max_depth)
        edge_stats = self.get_edges_per_node_stats()
        
        return {
            'num_nodes': self.get_num_nodes(),
            'num_edges': self.get_num_edges(),
            'graph_depth': self.compute_graph_depth(max_depth),
            'mean_edges_per_node': edge_stats['mean'],
            'median_edges_per_node': edge_stats['median'],
            'min_edges_per_node': edge_stats['min'],
            'max_edges_per_node': edge_stats['max'],
            'nodes_per_level': {level: len(nodes) for level, nodes in sorted(levels.items())},
            'total_paths': self.count_paths_dag(max_depth),
            'num_leaf_nodes': len(self.get_leaf_nodes()),
            'num_root_nodes': len(self.get_root_nodes()),
        }


def load_call_graph_from_json(data: Any) -> CallGraph:
    """
    Load a CallGraph from the merged_call_graph.json format.
    
    Supports multiple formats:
    1. Direct list of file entries: [{file: ..., functions: [...]}, ...]
    2. Wrapped format: {call_graph: [{file: ..., functions: [...]}, ...]}
    
    Also handles both old and new nested call graph formats:
    - Old format: functions_invoked is a list of strings
    - New format: functions_invoked is a list of nested dicts with 'function' key
    
    Args:
        data: List or dictionary loaded from merged_call_graph.json
    
    Returns:
        CallGraph instance populated with the data.
    """
    graph = CallGraph()
    
    # Handle both direct list format and wrapped dict format
    if isinstance(data, list):
        call_graph_data = data
    elif isinstance(data, dict):
        call_graph_data = data.get('call_graph', data.get('files', []))
        # If still a dict (not a list), try to extract the list
        if isinstance(call_graph_data, dict):
            call_graph_data = []
    else:
        call_graph_data = []
    
    def extract_invoked_functions(functions_invoked: List, caller_name: str) -> None:
        """
        Recursively extract function names from functions_invoked.
        Handles both old format (strings) and new nested format (dicts).
        """
        for invoked in functions_invoked:
            if isinstance(invoked, str):
                # Old format: direct string
                if invoked:
                    graph.add_edge(caller_name, invoked)
            elif isinstance(invoked, dict):
                # New nested format: dict with 'function' key
                invoked_name = invoked.get('function', '')
                if invoked_name:
                    graph.add_edge(caller_name, invoked_name)
                    # Recursively process nested callees
                    nested_invoked = invoked.get('functions_invoked', [])
                    if nested_invoked:
                        extract_invoked_functions(nested_invoked, invoked_name)
    
    for file_entry in call_graph_data:
        functions = file_entry.get('functions', [])
        
        for func_entry in functions:
            func_name = func_entry.get('function', '')
            if not func_name:
                continue
            
            # Add the function as a node
            graph.add_node(func_name)
            
            # Add edges for functions_invoked (handles both old and new formats)
            functions_invoked = func_entry.get('functions_invoked', [])
            extract_invoked_functions(functions_invoked, func_name)
    
    return graph


def print_statistics(stats: Dict[str, Any], indent: int = 0) -> None:
    """
    Print statistics in a formatted way.
    
    Args:
        stats: Statistics dictionary from CallGraph.get_statistics()
        indent: Indentation level for nested output.
    """
    prefix = "  " * indent
    
    print(f"{prefix}=" * 60)
    print(f"{prefix}CALL GRAPH STATISTICS")
    print(f"{prefix}=" * 60)
    print()
    
    print(f"{prefix}BASIC METRICS:")
    print(f"{prefix}-" * 40)
    print(f"{prefix}  Number of Nodes: {stats['num_nodes']}")
    print(f"{prefix}  Number of Edges: {stats['num_edges']}")
    print(f"{prefix}  Graph Depth: {stats['graph_depth']}")
    print()
    
    print(f"{prefix}EDGES PER NODE:")
    print(f"{prefix}-" * 40)
    print(f"{prefix}  Mean: {stats['mean_edges_per_node']:.2f}")
    print(f"{prefix}  Median: {stats['median_edges_per_node']:.2f}")
    print(f"{prefix}  Min: {stats['min_edges_per_node']}")
    print(f"{prefix}  Max: {stats['max_edges_per_node']}")
    print()
    
    print(f"{prefix}NODE CLASSIFICATION:")
    print(f"{prefix}-" * 40)
    print(f"{prefix}  Leaf Nodes (Level 0): {stats['num_leaf_nodes']}")
    print(f"{prefix}  Root Nodes (no callers): {stats['num_root_nodes']}")
    print()
    
    print(f"{prefix}NODES PER LEVEL:")
    print(f"{prefix}-" * 40)
    nodes_per_level = stats['nodes_per_level']
    for level in sorted(nodes_per_level.keys()):
        count = nodes_per_level[level]
        print(f"{prefix}  Level {level}: {count} nodes")
    print()
    
    print(f"{prefix}PATH ANALYSIS:")
    print(f"{prefix}-" * 40)
    print(f"{prefix}  Total Possible Paths (after breaking cycles): {stats['total_paths']}")
    print()
    print(f"{prefix}=" * 60)


def generate_sample_callstacks(
    graph: CallGraph,
    levels: Dict[int, Set[str]],
    output_path: str,
    max_samples_per_level: int = 10
) -> None:
    """
    Generate sample callstacks for each level and write them to a file.
    
    For each level, picks up to max_samples_per_level nodes and traces their
    call paths down to leaf nodes, formatting them in a tree-style indentation.
    
    Args:
        graph: The CallGraph instance
        levels: Dictionary mapping level number to set of nodes at that level
        output_path: Path to write the sample callstacks
        max_samples_per_level: Maximum number of sample callstacks per level (default: 10)
    """
    
    def build_callstack_tree(node: str, visited: set, depth: int = 0, max_depth: int = 20) -> list:
        """
        Build a tree representation of callstacks starting from a node.
        Returns a list of (depth, function_name) tuples for tree-style printing.
        """
        if depth > max_depth or node in visited:
            return []
        
        result = [(depth, node)]
        visited.add(node)
        
        # Get callees (functions this node calls)
        callees = sorted(graph.get_outgoing_edges(node))
        for callee in callees[:5]:  # Limit to 5 callees per node to avoid explosion
            result.extend(build_callstack_tree(callee, visited.copy(), depth + 1, max_depth))
        
        return result
    
    with open(output_path, 'w') as f:
        f.write("=" * 80 + "\n")
        f.write("SAMPLE CALLSTACKS BY LEVEL\n")
        f.write("=" * 80 + "\n")
        f.write(f"Max {max_samples_per_level} samples per level, tree-style indentation\n")
        f.write("=" * 80 + "\n\n")
        
        for level in sorted(levels.keys(), reverse=True):  # Start from highest level (root-like)
            nodes = sorted(levels[level])
            sample_nodes = nodes[:max_samples_per_level]
            
            f.write(f"\n{'=' * 60}\n")
            f.write(f"LEVEL {level} ({len(nodes)} total nodes, showing {len(sample_nodes)} samples)\n")
            f.write(f"{'=' * 60}\n\n")
            
            for i, node in enumerate(sample_nodes, 1):
                f.write(f"--- Sample {i}: {node} ---\n")
                
                # Build the callstack tree
                callstack = build_callstack_tree(node, set())
                
                for depth, func_name in callstack:
                    indent = "│   " * depth
                    if depth > 0:
                        prefix = "├── "
                    else:
                        prefix = ""
                    f.write(f"{indent}{prefix}{func_name}\n")
                
                f.write("\n")
        
        f.write("\n" + "=" * 80 + "\n")
        f.write("END OF SAMPLE CALLSTACKS\n")
        f.write("=" * 80 + "\n")
