"""
Issue Deduper module for removing duplicate issues from analyzer output.

This module provides functionality to deduplicate issues generated by analyzers
(code_analyzer, git_simple_diff_analyzer, or trace_analyzer) before HTML report
generation. Unlike issue_tracking_deduper which deduplicates against external
issue tracking systems, this deduper works entirely within the analysis pipeline.

Key Features:
- Exact duplicate detection using content hashing
- Semantic duplicate detection using vector similarity
- Repository-specific vector database storage
- Fresh state on each run (database wiped at start)

Usage:
    from hindsight.dedupers.issue_deduper import IssueDeduper
    
    # Initialize with artifacts directory
    deduper = IssueDeduper(
        artifacts_dir="~/llm_artifacts/corelocation",
        threshold=0.85
    )
    
    # Deduplicate issues
    unique_issues = deduper.dedupe(issues)
    
    # Get statistics
    stats = deduper.get_stats()
    
    # Cleanup
    deduper.cleanup()

Or using context manager:
    with IssueDeduper(artifacts_dir="~/llm_artifacts/corelocation") as deduper:
        unique_issues = deduper.dedupe(issues)

Or using convenience function:
    from hindsight.dedupers.issue_deduper import dedupe_issues
    
    unique_issues = dedupe_issues(
        issues=issues,
        artifacts_dir="~/llm_artifacts/corelocation"
    )
"""

# Apply numpy binary compatibility warnings filter BEFORE any imports
# This must be done early to prevent RuntimeWarning from being raised as an error
# when importing sentence-transformers or torch on older Python versions (e.g., 3.9)
import warnings
warnings.filterwarnings(
    "ignore",
    message=".*numpy\\.dtype size changed.*",
    category=RuntimeWarning
)
warnings.filterwarnings(
    "ignore",
    message=".*numpy\\.ufunc size changed.*",
    category=RuntimeWarning
)

from .deduper import (
    IssueDeduper,
    dedupe_issues,
    DeduplicationError,
    EmbeddingGenerationError,
    VectorStoreError,
)
from .config import (
    DEFAULT_SIMILARITY_THRESHOLD,
    EXACT_MATCH_THRESHOLD,
    DEFAULT_BATCH_SIZE,
    COLLECTION_NAME,
    VECTOR_DB_SUBDIR,
)
from .issue_ingester import IssueIngester
from .duplicate_detector import DuplicateDetector

__all__ = [
    # Main classes
    "IssueDeduper",
    "IssueIngester",
    "DuplicateDetector",
    # Convenience function
    "dedupe_issues",
    # Exceptions
    "DeduplicationError",
    "EmbeddingGenerationError",
    "VectorStoreError",
    # Configuration
    "DEFAULT_SIMILARITY_THRESHOLD",
    "EXACT_MATCH_THRESHOLD",
    "DEFAULT_BATCH_SIZE",
    "COLLECTION_NAME",
    "VECTOR_DB_SUBDIR",
]
