"""
HTML report parser for StaticIntelligence/LLM static analyzer reports.

This module provides parsers for HTML reports generated by LLM-based
static analysis tools, extracting issues for deduplication matching.

IMPORTANT: These HTML formats may change in the future. The parser includes
format validation to detect when the format has changed and provide clear
error messages to users.
"""

import json
import logging
import re
import hashlib
from pathlib import Path
from typing import List, Optional, Dict, Any, Tuple

from .base_parser import BaseReportParser
from ..deduper.issue import Issue

logger = logging.getLogger("issue_tracking_deduper.html_parser")


class FormatValidationError(Exception):
    """
    Raised when the HTML report format has changed or is not recognized.
    
    This error indicates that the parser detected a format change and
    the user should check for updates to the parser.
    """
    pass


class StaticIntelligenceParser(BaseReportParser):
    """
    Parser for StaticIntelligence HTML reports.
    
    These reports contain issues in a JavaScript variable `issuesData`
    with a JSON structure containing an array of issues.
    
    Supported report types:
    - repo_analysis_*.html (LLM static analyzer reports)
    - StaticIntelligence reports with issuesData JSON
    
    Format Validation:
    - The parser validates the expected structure of issues
    - If the format has changed, a FormatValidationError is raised
    - Required fields: 'issue' (title)
    - Expected fields: 'file', 'functionName', 'line', 'category', 'severity'
    """
    
    # Current format version (update when format changes)
    FORMAT_VERSION = "1.0"
    
    # Patterns to identify StaticIntelligence reports
    TITLE_PATTERNS = [
        r'<title>StaticIntelligence.*</title>',
        r'<title>.*analysis report.*</title>',
    ]
    
    # Pattern to extract issuesData JSON - match until the closing of the issues array
    # This is a more robust pattern that handles nested structures
    ISSUES_DATA_PATTERN = r'const\s+issuesData\s*=\s*\{[^{]*"issues"\s*:\s*\['
    
    # Required fields that must be present in each issue
    REQUIRED_FIELDS = ['issue']
    
    # Expected fields that should be present (for format validation)
    # Support both naming conventions (camelCase and snake_case)
    EXPECTED_FIELDS = ['file', 'file_path', 'functionName', 'function_name', 'line', 'line_number', 'category', 'severity']
    
    # Field name mappings (alternative names -> canonical names)
    FIELD_MAPPINGS = {
        'file_path': 'file',
        'function_name': 'functionName',
        'line_number': 'line',
    }
    
    # Minimum percentage of expected fields that must be present
    MIN_EXPECTED_FIELD_RATIO = 0.5
    
    def can_parse(self, report_path: Path) -> bool:
        """
        Check if this parser can handle the given report.
        
        Args:
            report_path: Path to the report file.
        
        Returns:
            True if this is a StaticIntelligence report.
        """
        if not report_path.exists():
            return False
        
        if report_path.suffix.lower() not in ['.html', '.htm']:
            return False
        
        try:
            # Read first 5KB to check for identifying patterns
            with open(report_path, 'r', encoding='utf-8') as f:
                header = f.read(5000)
            
            # Check for title patterns
            for pattern in self.TITLE_PATTERNS:
                if re.search(pattern, header, re.IGNORECASE):
                    return True
            
            # Check for issuesData variable
            if 'issuesData' in header or 'const issuesData' in header:
                return True
            
            # Check filename patterns
            filename = report_path.name.lower()
            if 'repo_analysis' in filename or 'staticintelligence' in filename:
                return True
            
        except Exception as e:
            logger.debug(f"Error checking report {report_path}: {e}")
        
        return False
    
    def parse(self, report_path: Path) -> List[Issue]:
        """
        Parse the HTML report and extract issues.
        
        Args:
            report_path: Path to the report file.
        
        Returns:
            List of Issue objects extracted from the report.
        
        Raises:
            FormatValidationError: If the report format has changed or is invalid.
        """
        logger.info(f"Parsing StaticIntelligence report: {report_path}")
        
        try:
            with open(report_path, 'r', encoding='utf-8') as f:
                content = f.read()
        except Exception as e:
            logger.error(f"Error reading report {report_path}: {e}")
            return []
        
        # Extract issuesData JSON
        issues_data = self._extract_issues_data(content)
        if not issues_data:
            raise FormatValidationError(
                f"Could not find 'issuesData' in report: {report_path}\n"
                f"The HTML report format may have changed. Please check for updates to the parser.\n"
                f"Expected: JavaScript variable 'const issuesData = {{\"issues\": [...]}}'"
            )
        
        # Get raw issues
        raw_issues = issues_data.get('issues', [])
        
        if not raw_issues:
            raise FormatValidationError(
                f"No issues found in 'issuesData.issues' array: {report_path}\n"
                f"The HTML report format may have changed or the report is empty."
            )
        
        # Validate format before parsing
        self._validate_format(raw_issues, report_path)
        
        logger.info(f"Found {len(raw_issues)} issues in report")
        
        # Parse issues
        issues = []
        for i, raw_issue in enumerate(raw_issues):
            issue = self._parse_issue(raw_issue, i, report_path)
            if issue:
                issues.append(issue)
        
        logger.info(f"Successfully parsed {len(issues)} issues")
        return issues
    
    def _validate_format(self, raw_issues: List[Dict[str, Any]], report_path: Path) -> None:
        """
        Validate that the issue format matches expected structure.
        
        This method checks that issues have the expected fields and raises
        a FormatValidationError if the format appears to have changed.
        
        Args:
            raw_issues: List of raw issue dictionaries.
            report_path: Path to the report file (for error messages).
        
        Raises:
            FormatValidationError: If the format validation fails.
        """
        if not raw_issues:
            return
        
        # Sample a few issues for validation (first, middle, last)
        sample_indices = [0]
        if len(raw_issues) > 1:
            sample_indices.append(len(raw_issues) // 2)
        if len(raw_issues) > 2:
            sample_indices.append(len(raw_issues) - 1)
        
        missing_required = []
        expected_field_counts = []
        
        for idx in sample_indices:
            issue = raw_issues[idx]
            
            # Check required fields
            for field in self.REQUIRED_FIELDS:
                if field not in issue or not issue[field]:
                    missing_required.append((idx, field))
            
            # Count expected fields present
            present_count = sum(1 for f in self.EXPECTED_FIELDS if f in issue)
            expected_field_counts.append(present_count)
        
        # Check if required fields are missing
        if missing_required:
            missing_details = ', '.join(f"issue[{idx}].{field}" for idx, field in missing_required)
            raise FormatValidationError(
                f"Required fields missing in report: {report_path}\n"
                f"Missing: {missing_details}\n"
                f"The HTML report format may have changed.\n"
                f"Expected required fields: {self.REQUIRED_FIELDS}\n"
                f"Parser version: {self.FORMAT_VERSION}"
            )
        
        # Check if expected fields ratio is too low
        avg_expected = sum(expected_field_counts) / len(expected_field_counts)
        expected_ratio = avg_expected / len(self.EXPECTED_FIELDS)
        
        if expected_ratio < self.MIN_EXPECTED_FIELD_RATIO:
            present_fields = set()
            for idx in sample_indices:
                present_fields.update(raw_issues[idx].keys())
            
            raise FormatValidationError(
                f"Issue format appears to have changed in report: {report_path}\n"
                f"Expected fields: {self.EXPECTED_FIELDS}\n"
                f"Found fields: {sorted(present_fields)}\n"
                f"Only {expected_ratio:.0%} of expected fields are present (minimum: {self.MIN_EXPECTED_FIELD_RATIO:.0%})\n"
                f"The HTML report format may have changed. Please check for updates to the parser.\n"
                f"Parser version: {self.FORMAT_VERSION}"
            )
        
        logger.debug(f"Format validation passed: {expected_ratio:.0%} of expected fields present")
    
    def get_format_name(self) -> str:
        """Return the name of the format this parser handles."""
        return "StaticIntelligence HTML Report"
    
    def get_report_metadata(self, report_path: Path) -> dict:
        """
        Extract metadata from the report.
        
        Args:
            report_path: Path to the report file.
        
        Returns:
            Dictionary containing report metadata.
        """
        metadata = {
            'format': self.get_format_name(),
            'path': str(report_path),
        }
        
        try:
            with open(report_path, 'r', encoding='utf-8') as f:
                content = f.read(10000)  # Read first 10KB for metadata
            
            # Extract title
            title_match = re.search(r'<title>(.*?)</title>', content, re.IGNORECASE)
            if title_match:
                metadata['title'] = title_match.group(1).strip()
            
            # Extract git info if present
            git_branch_match = re.search(r'git-badge.*?branch.*?>(.*?)<', content, re.IGNORECASE | re.DOTALL)
            if git_branch_match:
                metadata['git_branch'] = git_branch_match.group(1).strip()
            
            # Count issues
            issues_data = self._extract_issues_data(content)
            if issues_data:
                metadata['issue_count'] = len(issues_data.get('issues', []))
            
        except Exception as e:
            logger.debug(f"Error extracting metadata: {e}")
        
        return metadata
    
    def _extract_issues_data(self, content: str) -> Optional[Dict[str, Any]]:
        """
        Extract the issuesData JSON from HTML content.
        
        Args:
            content: The HTML content.
        
        Returns:
            Parsed JSON data, or None if not found.
        """
        # Find the start of issuesData
        start_match = re.search(r'const\s+issuesData\s*=\s*', content)
        if not start_match:
            # Try without 'const'
            start_match = re.search(r'issuesData\s*=\s*', content)
        
        if not start_match:
            logger.debug("Could not find issuesData in content")
            return None
        
        # Extract the JSON object starting from the match
        json_start = start_match.end()
        
        # Find the matching closing brace by counting braces
        json_str = self._extract_json_object(content, json_start)
        
        if not json_str:
            logger.debug("Could not extract JSON object from issuesData")
            return None
        
        # Clean up the JSON string
        json_str = self._clean_json_string(json_str)
        
        try:
            return json.loads(json_str)
        except json.JSONDecodeError as e:
            logger.warning(f"Failed to parse issuesData JSON: {e}")
            # Try to extract just the issues array
            return self._extract_issues_array_fallback(content)
    
    def _extract_json_object(self, content: str, start_pos: int) -> Optional[str]:
        """
        Extract a JSON object from content starting at the given position.
        
        Uses brace counting to find the matching closing brace.
        
        Args:
            content: The full content string.
            start_pos: Position where the JSON object starts (at the opening brace).
        
        Returns:
            The extracted JSON string, or None if extraction fails.
        """
        if start_pos >= len(content) or content[start_pos] != '{':
            return None
        
        brace_count = 0
        in_string = False
        escape_next = False
        
        for i in range(start_pos, len(content)):
            char = content[i]
            
            if escape_next:
                escape_next = False
                continue
            
            if char == '\\' and in_string:
                escape_next = True
                continue
            
            if char == '"' and not escape_next:
                in_string = not in_string
                continue
            
            if in_string:
                continue
            
            if char == '{':
                brace_count += 1
            elif char == '}':
                brace_count -= 1
                if brace_count == 0:
                    return content[start_pos:i + 1]
        
        return None
    
    def _clean_json_string(self, json_str: str) -> str:
        """
        Clean up a JSON string extracted from JavaScript.
        
        This method handles:
        - Trailing commas (invalid in JSON)
        - Literal newlines/tabs inside string values
        
        Note: We do NOT strip JavaScript comments with regex because that would
        incorrectly match URLs like "rdar://problem/..." inside strings.
        
        Args:
            json_str: The raw JSON string.
        
        Returns:
            Cleaned JSON string ready for parsing.
        """
        # The JSON may have literal newlines inside string values which is invalid.
        # We need to escape them properly. We'll process character by character
        # to handle this correctly, while also removing trailing commas.
        result = []
        in_string = False
        escape_next = False
        i = 0
        
        while i < len(json_str):
            char = json_str[i]
            
            if escape_next:
                # Previous char was backslash, this char is escaped
                result.append(char)
                escape_next = False
                i += 1
                continue
            
            if char == '\\' and in_string:
                # Backslash in string - next char is escaped
                result.append(char)
                escape_next = True
                i += 1
                continue
            
            if char == '"':
                # Toggle string state
                in_string = not in_string
                result.append(char)
            elif in_string:
                # Inside a string - escape control characters
                if char == '\n':
                    result.append('\\n')
                elif char == '\r':
                    result.append('\\r')
                elif char == '\t':
                    result.append('\\t')
                elif ord(char) < 32:
                    # Other control characters
                    result.append(f'\\u{ord(char):04x}')
                else:
                    result.append(char)
            else:
                # Outside string - handle trailing commas
                if char == ',':
                    # Look ahead to see if this is a trailing comma
                    j = i + 1
                    while j < len(json_str) and json_str[j] in ' \t\n\r':
                        j += 1
                    if j < len(json_str) and json_str[j] in ']}':
                        # This is a trailing comma, skip it
                        i += 1
                        continue
                result.append(char)
            
            i += 1
        
        return ''.join(result)
    
    def _extract_issues_array_fallback(self, content: str) -> Optional[Dict[str, Any]]:
        """
        Fallback method to extract issues array directly.
        
        Args:
            content: The HTML content.
        
        Returns:
            Dictionary with issues array, or None if not found.
        """
        # Try to find the issues array directly
        pattern = r'"issues"\s*:\s*(\[[\s\S]*?\])\s*[,}]'
        match = re.search(pattern, content, re.DOTALL)
        
        if not match:
            return None
        
        try:
            issues_array = json.loads(match.group(1))
            return {'issues': issues_array}
        except json.JSONDecodeError:
            return None
    
    def _parse_issue(
        self,
        raw_issue: Dict[str, Any],
        index: int,
        report_path: Path
    ) -> Optional[Issue]:
        """
        Parse a single issue from the raw JSON data.
        
        Args:
            raw_issue: The raw issue dictionary from JSON.
            index: The index of the issue in the array.
            report_path: Path to the source report.
        
        Returns:
            An Issue object, or None if parsing fails.
        """
        try:
            # Extract required fields
            title = raw_issue.get('issue', '')
            if not title:
                logger.debug(f"Issue {index} has no title, skipping")
                return None
            
            # Build description from available fields
            description_parts = []
            
            # Add impact if available
            impact = raw_issue.get('impact', '')
            if impact:
                description_parts.append(f"Impact: {impact}")
            
            # Add evidence/validation reasoning
            evidence = raw_issue.get('evidence', '') or raw_issue.get('validationReasoning', '')
            if evidence:
                description_parts.append(evidence)
            
            # Add potential solution
            solution = raw_issue.get('potentialSolution', '') or raw_issue.get('suggestion', '')
            if solution:
                description_parts.append(f"Suggested fix: {solution}")
            
            # Add description if available
            desc = raw_issue.get('description', '')
            if desc:
                description_parts.insert(0, desc)
            
            description = '\n\n'.join(description_parts) if description_parts else title
            
            # Generate unique ID
            issue_id = self._generate_issue_id(raw_issue, index, report_path)
            
            # Extract optional fields - support both naming conventions
            file_path = raw_issue.get('file', '') or raw_issue.get('file_path', '')
            function_name = raw_issue.get('functionName', '') or raw_issue.get('function_name', '')
            severity = raw_issue.get('severity', '')
            category = raw_issue.get('category', '') or raw_issue.get('oldCategory', '')
            line = raw_issue.get('line', '') or raw_issue.get('line_number', '')
            
            # Build raw HTML representation for reference
            raw_html = json.dumps(raw_issue, indent=2)
            
            return Issue(
                id=issue_id,
                title=title,
                description=description,
                file_path=file_path if file_path else None,
                function_name=function_name if function_name else None,
                severity=severity if severity else None,
                category=category if category else None,
                raw_html=raw_html,
            )
            
        except Exception as e:
            logger.warning(f"Error parsing issue {index}: {e}")
            return None
    
    def _generate_issue_id(
        self,
        raw_issue: Dict[str, Any],
        index: int,
        report_path: Path
    ) -> str:
        """
        Generate a unique ID for an issue.
        
        Args:
            raw_issue: The raw issue dictionary.
            index: The index of the issue.
            report_path: Path to the source report.
        
        Returns:
            A unique issue ID string.
        """
        # Create a hash from key fields
        key_parts = [
            raw_issue.get('issue', ''),
            raw_issue.get('file', ''),
            raw_issue.get('functionName', ''),
            str(raw_issue.get('line', '')),
        ]
        key_string = '|'.join(key_parts)
        hash_value = hashlib.md5(key_string.encode()).hexdigest()[:8]
        
        return f"si_{report_path.stem}_{index}_{hash_value}"


class GenericHTMLParser(BaseReportParser):
    """
    Generic HTML parser that attempts to extract issues from any HTML report.
    
    This parser is used as a fallback when no specific parser matches.
    It looks for common patterns in HTML reports to extract issues.
    """
    
    def can_parse(self, report_path: Path) -> bool:
        """
        Check if this parser can handle the given report.
        
        This parser can handle any HTML file as a fallback.
        
        Args:
            report_path: Path to the report file.
        
        Returns:
            True if this is an HTML file.
        """
        if not report_path.exists():
            return False
        
        return report_path.suffix.lower() in ['.html', '.htm']
    
    def parse(self, report_path: Path) -> List[Issue]:
        """
        Parse the HTML report and extract issues.
        
        This generic parser looks for common issue patterns in HTML.
        
        Args:
            report_path: Path to the report file.
        
        Returns:
            List of Issue objects extracted from the report.
        """
        logger.info(f"Parsing HTML report with generic parser: {report_path}")
        
        try:
            from bs4 import BeautifulSoup
        except ImportError:
            logger.error("beautifulsoup4 is required for HTML parsing. Install with: pip install beautifulsoup4")
            return []
        
        try:
            with open(report_path, 'r', encoding='utf-8') as f:
                content = f.read()
        except Exception as e:
            logger.error(f"Error reading report {report_path}: {e}")
            return []
        
        soup = BeautifulSoup(content, 'html.parser')
        issues = []
        
        # Look for common issue container patterns
        issue_containers = (
            soup.find_all(class_=re.compile(r'issue|finding|problem|bug|error|warning', re.I)) or
            soup.find_all(attrs={'data-issue': True}) or
            soup.find_all(attrs={'data-finding': True})
        )
        
        for i, container in enumerate(issue_containers):
            issue = self._parse_container(container, i, report_path)
            if issue:
                issues.append(issue)
        
        logger.info(f"Generic parser found {len(issues)} issues")
        return issues
    
    def get_format_name(self) -> str:
        """Return the name of the format this parser handles."""
        return "Generic HTML Report"
    
    def _parse_container(
        self,
        container,
        index: int,
        report_path: Path
    ) -> Optional[Issue]:
        """
        Parse an issue from an HTML container element.
        
        Args:
            container: BeautifulSoup element containing the issue.
            index: The index of the issue.
            report_path: Path to the source report.
        
        Returns:
            An Issue object, or None if parsing fails.
        """
        try:
            # Try to extract title from various common patterns
            title_elem = (
                container.find(class_=re.compile(r'title|heading|summary', re.I)) or
                container.find(['h1', 'h2', 'h3', 'h4', 'strong'])
            )
            title = title_elem.get_text(strip=True) if title_elem else ''
            
            if not title:
                # Use first text content as title
                title = container.get_text(strip=True)[:200]
            
            if not title:
                return None
            
            # Try to extract description
            desc_elem = container.find(class_=re.compile(r'description|detail|body|content', re.I))
            description = desc_elem.get_text(strip=True) if desc_elem else container.get_text(strip=True)
            
            # Generate ID
            hash_value = hashlib.md5(title.encode()).hexdigest()[:8]
            issue_id = f"html_{report_path.stem}_{index}_{hash_value}"
            
            return Issue(
                id=issue_id,
                title=title[:500],  # Limit title length
                description=description,
                raw_html=str(container),
            )
            
        except Exception as e:
            logger.debug(f"Error parsing container {index}: {e}")
            return None
